// AUTO-GENERATED by scripts/extract-schematics.mjs — do not edit.
// CAE Falcon 50 Operating Handbook schematics (Rev 1 Aug 2025), served as
// static images so they are cached by the service worker and kept out of JS.
const base = import.meta.env.BASE_URL;
export const HANDBOOK_IMG: Record<string, string> = {
  bleed: base + "handbook/bleed.png",
  dcelec: base + "handbook/dcelec.png",
  acelec: base + "handbook/acelec.png",
  fuel: base + "handbook/fuel.png",
  hyd: base + "handbook/hyd.png",
};
